### ISSUE TITLE
Does not provide a subscript operator

### ISSUE THREAD

**Issue by tiagomiguelcs** [CallmeNezha/SimpleDBSCAN#1]
Hi,

I can't compile your code, error as follows:

<img width="722" alt="error_" src="https://user-images.githubusercontent.com/23378935/35579085-ba09566e-05dd-11e8-9ae5-557d6d8b7a34.png">

Thank you,

**Comment by CallmeNezha** [comment]
Thank you very much for your notice. I have fix it now 😄
