### ISSUE TITLE
Why the output cluster size smaller than the minpts?

### ISSUE THREAD

**Issue by zouyoucheng27** [CallmeNezha/SimpleDBSCAN#9]
![image](https://user-images.githubusercontent.com/67536833/220271416-19a8ab58-2ced-4591-a7c2-b80ec2cd3597.png)
I use the code test in my data.And I set the minpts 4. I was thinking that the output cluster size more than the minpts, but sometimes the output print that smaller than the minpts, like 1 or 2. There is no other points in neighborhood.Why not the point index in the set of noise?

**Comment by CallmeNezha** [comment]
Please attach the dataset you used so I can reproduce this result. Alternatively, if you have found any reason why it happenes , that would be greatly appreciated.

**Comment by zouyoucheng27** [comment]
Thanks for your kind reply. I have solve this question.

**Comment by HenryParsa** [comment]
I have the same issue.
@zouyoucheng27  could you please provide your solution?

this is from the system log:
APPLYING DBSCAN ->  MINIMUM DISTANCE: 0.4    MIN POINTS IN CLUSTER: 3
******* FAULT IN CLUSTERING: CLUSTER SIZE ERROR  --->>> CLUSTER SIZE: 2   OCCURRED ON CLUSTER NUMBER: 2
